version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  apigateway:
    build: ../apigateway
    ports:
      - "8068:8068"
    environment:
      USER_SERVICE_URI: http://user-service:8080
      AUTHENTIFICATION_SERVICE_URI: http://auth-service:8082
      ORDER_SERVICE_URI: http://order-service:8084
    depends_on:
      - postgres
      - redis

  auth-service:
    build: ../authentificationservice
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      REDIS_HOST: redis

  user-service:
    build: ../userservice
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userservice_db

  order-service:
    build: ../orderservice
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db