server:
  port: 8068
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: ${USER_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/api/users/**
        - id: authenticationservice
          uri: ${AUTHENTICATION_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/auth/**
        - id: orderservice
          uri: ${ORDER_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/api/orders/**
        - id: paymentservice
          uri: ${PAYMENT_SERVICE_URI:http://localhost:8088}
          predicates:
            - Path=/api/payments/**